name: Docker Image CI

on:
  [workflow_dispatch]

jobs:

  publish_images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./client --file Dockerfile --tag vinaybadami/docker-course-client:latest
    - name: push
      run: |
        docker login -u vinaybadami -p ${{secrets.DOCKERHUB_TOKEN}}
        docker push vinaybadami/docker-course-client:latest
