name: Docker Image CI

on:
  [workflow_dispatch]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:

  publish_images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker client image
      run: docker build ./client --file Dockerfile --tag vinaybadami/docker-course-client:latest
    - name: Build the Docker server image
      run: docker build ./server --file Dockerfile --tag vinaybadami/docker-course-server:latest
    - name: Build the Docker worker image
      run: docker build ./worker --file Dockerfile --tag vinaybadami/docker-course-worker:latest

    - name: push
      run: |
        docker login -u vinaybadami -p ${{secrets.DOCKERHUB_TOKEN}}
        docker push vinaybadami/docker-course-client:latest
